### ISSUE TITLE
Games not being marked

### ISSUE THREAD

**Issue by lProvosl** [Revadike/SteamWebIntegration#11]
For some reason I cannot get games to be marked with this anymore.  I don't think I have done anything that would have caused this.  I did here there was a Steam update and also a Tampermonkey update.  I am not sure if those changes are what caused this issue.  I have got ESGST to work on steamgifts but I prefer  this program as it can also check other sites.

https://i.imgur.com/EMl4Lad.png

I am only getting this error on console
0: Unable to get property 'rgIgnoredApps' of undefined or null reference

**Comment by Royalgamer06** [comment]
Try clearing storage:
![image](https://user-images.githubusercontent.com/4411977/47077735-e98e0880-d201-11e8-908b-641ff87c6402.png)

**Comment by lProvosl** [comment]
Sorry but I don't have the storage tab just Editor, Settings, and Externals.  I am running Tampermonkey 4.8.5847.  Thanks

**Comment by Luckz** [comment]
You need to first change Tampermonkey's `Settings -> General -> Config mode` to `Advanced`.

**Comment by lProvosl** [comment]
Thanks, I found and cleared the storage.  

It still doesn't seem to be working but ESGST still is.  I not sure what the problem is at all.

**Comment by Luckz** [comment]
Does the browser console show any new errors?
Are you sure you're running the newest version of the script?
Does it not work any websites, or just not on SteamGifts? Google search is an easy test.

**Comment by lProvosl** [comment]
I am getting a few errors
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://www.steamgifts.com/null
Refused to connect to "https://www.steamtrades.com": URL is blacklisted
SCRIPT5007: SCRIPT5007: Unable to get property 'rgIgnoredApps' of undefined or null reference

I think it is the fact I am using Edge browser maybe.

**Comment by Royalgamer06** [comment]
What does it say when you visit? https://store.steampowered.com/dynamicstore/userdata
