### ISSUE TITLE
Fanatical bundle pages do not update the ownership status

### ISSUE THREAD

**Issue by redion1992** [Revadike/SteamWebIntegration#12]
If I go to a bundle page on the Fanatical website (eg. https://www.fanatical.com/en/bundle/tabletop-bundle), and click on one of the game icons, the script successfully injects the ownership status for that game to the details window below. However, if I attempt to view another game, the ownership status is not updated for the new "View on Steam" link, as the content of the link is updated via a script, rather than showing and hiding different elements. Is it possible to refresh the shown status based on the link address updating?

**Comment by Luckz** [comment]
Ignoring the discussion about whether it makes sense to monitor all URLs for changes,
you can very easily see whether you own games from a Fanatical bundle via [Barter](https://barter.vg/bundles/8/) or [SteamGifts](https://www.steamgifts.com/discussions/deals/search?q=Fanatical).

**Comment by Revadike** [comment]
This was fixed in V1.8.0 and further improved in V1.8.1
