### ISSUE TITLE
Changing attributes (src, href) not detected

### ISSUE THREAD

**Issue by Revadike** [Revadike/SteamWebIntegration#16]

**Comment by bestpika** [comment]
https://github.com/Revadike/SteamWebIntegration/blob/45c3bf5fa29d23e140176e9fc383c2909d62890f/Steam%20Web%20Integration.user.js#L512
It looks like you've only been observing `added` and that's it.

**Comment by Revadike** [comment]
> https://github.com/Revadike/SteamWebIntegration/blob/45c3bf5fa29d23e140176e9fc383c2909d62890f/Steam%20Web%20Integration.user.js#L512
> 
> 
> It looks like you've only been observing `added` and that's it.

https://github.com/kapetan/jquery-observe
I don't think it provides an observer for `changed`. 
Perhaps I should switch to plain [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).
I think I considered this in the past, but some reason decided not do it.
I forgot why though.

**Comment by dokiiin** [comment]
Not detecting game ownership and other game specific flags on fanatical, when looking at bundle page at product details (game info) slider . All games are shown as unowned and game with cards, even if I own the game and game has no cards.

**Comment by Luckz** [comment]
> Not detecting game ownership and other game specific flags on fanatical, when looking at bundle page at product details (game info) slider . All games are shown as unowned and game with cards, even if I own the game and game has no cards.

If you really need to see these on Fanatical, you could always use **"Clear and run"** from your right-click or extension menu.
![image](https://user-images.githubusercontent.com/224748/166395932-c96818c1-62a3-4955-bc06-b6319a8ab87a.png)

..but why don't you just use a less disgusting website to browse their bundle contents?
https://barter.vg/bundle/6142/ , https://www.steamgifts.com/discussion/i2qT2/ or even ITAD, gg deals, ...

**Comment by dokiiin** [comment]
> If you really need to see these on Fanatical, you could always use **"Clear and run"** from your right-click or extension menu.

That only works for one game at a time, switching to the next shows the previous game attributes.

**Comment by Luckz** [comment]
Sure.
