### ISSUE TITLE
Flag for Subscribed Mods via user listing

### ISSUE THREAD

**Issue by ghost** [Revadike/SteamWebIntegration#19]
Steam Workshop normally flags mods you are subscribed to when you're viewing them in the 'Browse' section of the game, the main directory so to speak, but when you're viewing the workshop section of a user's profile, there is no indication whether you are subscribed or not.

Here is an example URL:
https://steamcommunity.com/id/st0m/myworkshopfiles/?appid=286160

Change the 'appid' to a game you own and 'id' to a mod author whose mods you've subscribed to, and you'll notice the checkmark won't be there (though you can still press the green + button which adds it until the page refreshes).

If you could correct this behavior, I would be forever grateful.

**Comment by Revadike** [comment]
After reviewing this issue, this seems more suitable for https://github.com/tfedor/AugmentedSteam/issues
Please, post your issue there.
