### ISSUE TITLE
 It will block the Google Verification pop-up on Nintendo's official website

### ISSUE THREAD

**Issue by mcpolarbear** [Revadike/SteamWebIntegration#23]

**Comment by mcpolarbear** [comment]
In other words, clicking the login button does not respond.

**Comment by Revadike** [comment]
It shouldn't block anyway. Could you be more precise?

**Comment by mcpolarbear** [comment]
Loading this plug-in, reCAPTCHA will not appear in the lower right corner of the page

**Comment by Revadike** [comment]
I don't think so. Maybe link the page you have problems with?

**Comment by Revadike** [comment]
I cannot reproduce this problem. The login page works fine for me.
