### ISSUE TITLE
request: more settings in 2.31 Hidden Games Manager

### ISSUE THREAD

**Issue by veebles** [Revadike/SteamWebIntegration#24]
Only Remove Followed Games
Only Remove Games Tagged [select list - 8.3 game tags] [+ Tag]
 &nbsp; &nbsp; &nbsp; &nbsp; [+ Tag] adds another Only Remove Games Tagged [select list - 8.3 game tags] line
 &nbsp; &nbsp; &nbsp; &nbsp; personally only need one tag, but reckon others may prefer more
 &nbsp; &nbsp; &nbsp; &nbsp; suggest running multiple tags sequentially not concurrently

Thanks again for all your hard work 🥇

**Comment by Revadike** [comment]
what?

**Comment by veebles** [comment]
main settings option 2.31 Hidden Games Manager
[eye + x] button on https://www.steamgifts.com/account/settings/giveaways/filters
popup "+ Add / remove hidden games:" currently has the following settings...
Add all owned games.
Add all ignored games.
Add all banned games (requires syncing delisted games in the settings menu).
Only remove games from text area.
Only remove owned games.
Only remove wishlisted games.
Only remove banned games (requires syncing delisted games in the settings menu).

what do you need me to clarify?
Followed games on Steam, similar but separate to Wishlist
Tags for dynamic selectlist from main settings option 8.3 Game Tags, edited via last button on top row of main settings [Manage Game Tags]

**Comment by veebles** [comment]
rotfl I just realised this is not the ESGST project, sorry about that mate, I clicked on the wrong link
