### ISSUE TITLE
[Suggestion] Setting for time period regarding dynamicContent

### ISSUE THREAD

**Issue by Eiion** [Revadike/SteamWebIntegration#28]
Add option to https://revadike.ga/swi/settings/ to let users set the time period for dynamicContent when the page gets checked. (Possibly with a minimum of 1.5 so they don't go overboard with it.)

**Comment by Revadike** [comment]
Done! Please check out https://github.com/Revadike/SteamWebIntegration/releases/tag/V1.12.0

**Comment by Luckz** [comment]
How do "observe" and "periodically" compare in performance terms (CPU, wakeups, RAM usage, browser slowdown)? Are there any use cases where observing isn't plainly better?

**Comment by Revadike** [comment]
> How do "observe" and "periodically" compare in performance terms (CPU, wakeups, RAM usage, browser slowdown)? Are there any use cases where observing isn't plainly better?

When js causes a lot of page changes, observing can slow down the page quite a bit.
