### ISSUE TITLE
[Suggestion] Add option to change background colours for icons.

### ISSUE THREAD

**Issue by Eiion** [Revadike/SteamWebIntegration#29]
Add option to https://revadike.ga/swi/settings/ to let users set the colour of the icon background (line 585 - background: rgba(0, 0, 0, 0.7);) in order to avoid having to manually edit the line just like there's options to adjust any other color on the settings page.

**Comment by Revadike** [comment]
Done! Please check out https://github.com/Revadike/SteamWebIntegration/releases/tag/V1.12.0
