### ISSUE TITLE
[Suggestion] Make SWI work on Gamivo

### ISSUE THREAD

**Issue by Eiion** [Revadike/SteamWebIntegration#30]
It would be great if SWI would also work on the shop listings for shops like (and aspecially as) Gamivo. If that could be included, that would be really great! If only it worked for whishlist games...

**Comment by Revadike** [comment]
Sadly not possible, as Gamivo doesn't have any sources to actual steam appids.

**Comment by Eiion** [comment]
I see. Allkeyshop has games sold at Gamivo listed though. Considering they must get their info somewhere, there should be a way to connect these listings with the Steam API, right?

**Comment by Revadike** [comment]
> I see.
> Allkeyshop has games sold by Gamivo listed though. Considering they must get their info somewhere, there should be a way to connect these listings with the Steam API, right?

I think they link them via game titles, which I cannot do.

**Comment by Eiion** [comment]
The both could be connected with e.g. the steamdb api. Something like that could make SWI work with all shops that don't supply direkt Steam links.

**Comment by Revadike** [comment]
> the steamdb api

no such thing

**Comment by Eiion** [comment]
How about utilizing Steam Spy's API or even Steam's API itself? I mean at least with Steam's own API it should be possible to push a game's name to it and receive app id and such back?

**Comment by Revadike** [comment]
> How about utilizing Steam Spy's API or even Steam's API itself? I mean at least with Steam's own API it should be possible to push a game's name to it and receive app id and such back?

I won't scan all webpage text for game titles. That will lead to too much false positives. Steam appids are the only way to go.

**Comment by Eiion** [comment]
Alright.
