### ISSUE TITLE
Breaks OnePlus.com

### ISSUE THREAD

**Issue by IrisNebula4700** [Revadike/SteamWebIntegration#31]
**Website: https://www.oneplus.com/**

The site is inoperable unless excluded from the script. It starts loading, renders the page and the minute the "[Steam Web Integration] Executing" message comes up in the console, it freezes. Tab process gets full CPU time, console shows nothing after the executing message, and tab is frozen.

**Google Chome** Version 77.0.3865.90 (Official Build) (64-bit)
**Tampermonkey** 4.8.41 (2019-05-06)
No other scripts on website, AdBlocker on/off makes no difference

**Comment by Revadike** [comment]
I added a domain black list in V1.9.7, you can now exclude this site.
