### ISSUE TITLE
Version 1.9.4 - Setting page does not display

### ISSUE THREAD

**Issue by C-O-S** [Revadike/SteamWebIntegration#32]
Script version 1.9.4:  when I now go to the settings page all that is displayed is the message : "Steam Web Integration not installed! Please make sure it is installed correctly and enabled, then refresh the page." 

This message persists through clearing, Tampermonkey factory resets for the script, and deleting an reinstalling.

My use case:
Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)
Tampermonkey 4.8.41

**Comment by Revadike** [comment]
V1.9.5 solved it
