### ISSUE TITLE
Setting wantDecommissioned causes most runs to fail

### ISSUE THREAD

**Issue by Bobogoobo** [Revadike/SteamWebIntegration#34]
Starting 1 or 2 days ago, I noticed icons weren't showing up 99% of the time on any website, using Firefox (latest version). The console has the following error for each icon that should be present:
```
TypeError: decommissioned.find is not a function eval line 2 > eval:380:44
    doApp moz-extension://<snip>/userscripts/Steam Web Integration.user.js?id=<snip>
    r eval:2
    d eval line 1 > Function:42
```
Which leads to this line:
`const app = decommissioned.find((obj) => obj.appid === appID.toString());`

I turned off the wantDecommissioned setting and the error no longer occurs.
Other settings such as wantLimited seem to be fine.

Thank you!

**Comment by Revadike** [comment]
Do you still have this issue with the latest version?

**Comment by Bobogoobo** [comment]
Actually I didn't have the issue either before or after updating to the latest version, after enabling the setting again to test just now. Could have been fixed in the previous version I had, but either way, the issue seems to be resolved.
