### ISSUE TITLE
barter.vg does not work on Firefox 77.0.1

### ISSUE THREAD

**Issue by BabyKiller** [Revadike/SteamWebIntegration#37]
After updating Firefox to version 77.0.1, the script for barter.vg stopped working. It seems that the problem with locking the CSP

**Comment by Semenox** [comment]
> 
> 
> After updating Firefox to version 77.0.1, the script for barter.vg stopped working. It seems that the problem with locking the CSP

I can confirm this too.

**Comment by bartervg** [comment]
I don't think anything related to CSP has changed on the site in the past week.

What is the error message? You should be able to see it by opening DevTools (F12 or Cmd + Opt + I)  and clicking the Console tab.

**Comment by BabyKiller** [comment]
I have a second computer, the problem remains... so the thing is in the site...
Same browser, same site, same script:
https://yadi.sk/i/XKOfjU3qVBH_RQ
https://yadi.sk/i/HS9MhU5u42XJow

**Comment by BabyKiller** [comment]
After updating Windows, Tampermonkey and restarting the computer, the problem disappeared on the second computer..

**Comment by bartervg** [comment]
Thanks for those screenshots. 

I'm excerpted what appears to be the relevant error 
![image](https://user-images.githubusercontent.com/28576132/84386251-fd4c6680-abbe-11ea-9f51-bf1250c559a4.png)

**Comment by Revadike** [comment]
Has this been resolved?

**Comment by BabyKiller** [comment]
> Has this been resolved?
Yes.
Thanks for the script!
