### ISSUE TITLE
[Suggestion] Please add Option to Scale Icon/Text Size...

### ISSUE THREAD

**Issue by Black3ird** [Revadike/SteamWebIntegration#39]
Dear Sir,

First of all thanks for keeping this Script alive as it's now a **Must** Install for me and I recommend it to whomever willing go beyond the Vanilla Steam Experience, good job. As I also must thank for the existence of https://revadike.com/swi/settings/ because before that I was custom editing into your ever increasing and getting complicated code as I prefer other set of Unicode that appeal to me like ♡ ☑ ☒ ☐ for wish, own, ignore and unown.

But with latest update, I'm just clueless to where to **Inject** my custom font sizing that I used to use as code of;

```
if (ignoredApps.includes(appID) && wantIgnores) { //if ignored and enabled
                html += "<span style='color: " + ignoredColor + " !important; font-size: 1.2em; font-weight: bold; cursor: help;' title='Game or DLC (" + appID + ") ignored on Steam\nLast updated: " + lcs + "'> " + ignoredIcon + "</span>"; //🛇
            }
```

from an Old copy of your Code where I injected the font-size and font-weight CSS properties because my Eyesight is not so good that I have difficulty to see your "Tiny" Icons to recognize what they meant. But now in the New copy of your Code it's;

```
if (settings.wantIgnores && ignoredApps && ignoredApps.includes(appID)) { // if ignored and enabled
            html += getIconHTML(settings.ignoredColor, `${subject} (${appID}) ignored`, llcs, settings.ignoredIcon); // 🛇
        }
```

And I'm totally **LOST** even what this means or where to inject my custom Font Sizing CSS as your Code is getting more and more "Complex" so that only you know what's what and what to do about my Font Sizing problem.

As an amateur programmer I can track down the code (I guess) to find the New Entry Point to Inject my font-size and font-weight CSS properties but it'll take time and then I thought why don't I ask the Author so that every possible user in my situation can use such feature without having to analyze or edit your good written Code.

...

So please add a "iconScaling" (font-size in em) and "iconsBold" (font-weight) and maybe also "textScaling" (for hover text) entries into https://revadike.com/swi/settings/ in the form of "Percentage" measurement of EM (or directly Percentage) told in https://www.w3schools.com/css/css_font_size.asp for **ALL** of your Script Icons so that;

font-size: 1.2em; font-weight: bold;

could be done at Script Settings Level instead of code injection to ever evolving Coding of yours.

Thanks for your time and I hope you can consider to Code this into your next Update before I mess with your code back and forth to find "where" to inject.

Best Regards.

**Comment by Revadike** [comment]
You can still implement it manually in the `getIconHTML` function.

**Comment by Revadike** [comment]
Done! Please check out https://github.com/Revadike/SteamWebIntegration/releases/tag/V1.12.0
