### ISSUE TITLE
[Suggestion] Showing SWI icons for each game only once on each webpage

### ISSUE THREAD

**Issue by AxJ11** [Revadike/SteamWebIntegration#43]
Hi, is it possible to do that if each of the groups of SWI icons is for the same game?

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/SteamWebIntegration/issues/36

**Comment by AxJ11** [comment]
Oh, sorry, I forgot that one.  So, any solution now?   BTW, I just completed a script about this but it's a customized fix per page.
