### ISSUE TITLE
SWI causes extreme freezes with Steamgifts 

### ISSUE THREAD

**Issue by Eiion** [Revadike/SteamWebIntegration#44]
For two days now there's really bad issues with Steamgifts now.
The reason I suspect SWI (besides Chrome) causing the issue is that everything else is newer and has been working well in the past while the last SWI update is from 39 days ago and the only thing having been updated right before the issues occurred is Chrome itself.

So here's the thing: I'm also using ESGST and when SWI is off while ESGST is on then everything works fine. If SWI is on and ESGST is off, then everything works fine as well. Both ESGST and SWI on though and you get in lag hell with cores of the CPU on 100% load. Loading in 6 pages on the Group page on Steamgifts takes 15 minutes - at least. Scrolling the page is not possible until everything is finished - unless you drag the scroll bar, that for some reason works. It's like surfing with dial-up modem in the late nineties all over again.

I'm assuming that something which got updated within Chrome causes both ESGST and SWI being somewhat incompatible with one another. But since ESGST's version is relatively new opposed to SWI I'd like to ask to check SWI for such issue and update it accordingly - if someone please could look into the issue.

**Comment by Eiion** [comment]
I've kept playing around with the settings and here's my findings for now:
I had SWI on Observe - switching it down to check every 1.5 seconds fixes the issue.
With SWI on Observe and every want deactivated it still has the issue which makes me believe that it might not even be an issue with Chrome but maybe Steam.
So until the error is fixed I guess I'll have to keep it on Check webpage every 1.5 seconds.

**Comment by Revadike** [comment]
I can explain. ESGST is an addon that adds a lot of custom elements to the site. These additions and changes are all detected by SWI (with Observe) and they're all getting processed. I already tried to optimize it as much as possible, but clearly its still taking a lot of processing power when a lot in the site is changing. I think checking every 1.5 is the solution for you. Or excluse steamgifts altogether.

**Comment by Eiion** [comment]
You see, the odd thing is that I always had both ESGST and SWI on at the same time with SWI on Observe, for years by now. And this wasn't an issue or causing any problems until now three days ago.
I'm aware of the extra load but, the website still works perfectly fine and there was hardly any waiting time besides a few seconds to load everything in. In now way did it come anywhere even remotely close to how it's now, which is basically unbearable non-usable slow.

Things suddenly turned from working perfectly fine in combination with one another to opposite of that. Hence the post in issues.

**Comment by Revadike** [comment]
Hmm, well, seeing that nothing has changed for SWI for some time now, I think it's safe to assume that the issue was caused by a change with ESGST.

**Comment by Eiion** [comment]
As I've said before: While the last update for ESGST is newer than SWI but it's still from a while ago (5th Dezember 2020). The only thing that did update was Chrome itself. And with ESGST being newer than SWI it's more likely to already have adapted more recent changes that came with Chrome updates.
Either way, it cannot be a change with ESGST if ESGST didn't change recently and the issues only showed up three days ago while before there simply was no issue. So I can't agree with your assumption.
I know, you could argue that the same logic applies to my point - hence my second sentence arguing why it makes more sense that SWI is at fault, especially when after changing its settings the issue appears to be circumvented.

**Comment by Revadike** [comment]
Merging this with https://github.com/Revadike/SteamWebIntegration/issues/14, lets discuss this issue there
