### ISSUE TITLE
Settings page problem

### ISSUE THREAD

**Issue by lProvosl** [Revadike/SteamWebIntegration#58]
Getting a warning when trying to edit settings of the script.   Running Brave Browser version 1.34.80.  Tried doing a factory reset and that didn't help.  Not sure if I have anything blocked or need to whitelist anything on this just had to reinstall windows so having to restore from tampermonkey save point.

```
Steam Web Integration not installed!
Please make sure it is installed correctly and enabled, then refresh the page.
```

**Comment by Revadike** [comment]
I use Brave too, and it seems working for me. Does the console (F12) say anything?

**Comment by lProvosl** [comment]
![Errors from F12](https://user-images.githubusercontent.com/4444608/149616111-6718bfa7-e910-4fee-a5ea-e77c11bd50e4.png)

There are error but I think from ESGST

**Comment by Revadike** [comment]
I have ESGST too, I tested it, and it still works. I don't know why it would detect. 
Also, `[Steam Web Integration] Executing` shouldn't be logged on that page.
This makes me think, you're on the wrong page or something.
Try visiting https://revadike.com/swi/settings/ directly.
You can also try incognito mode, with only SWI userscript enabled.

**Comment by lProvosl** [comment]
I tried visiting the shortcut you listed sorry posted wrong screen before. 
![Steam Web Intigration](https://user-images.githubusercontent.com/4444608/149645877-015f4350-3606-44eb-9437-1bd7915ae2c9.png)

**Comment by Revadike** [comment]
> I tried visiting the shortcut you listed sorry posted wrong screen before. ![Steam Web Intigration](https://user-images.githubusercontent.com/4444608/149645877-015f4350-3606-44eb-9437-1bd7915ae2c9.png)

That error isn't relevant to this issue. It just complains I do not have a site icon, but that's fine. Unless someone wants to design an icon for SWI? :)

**Comment by Luckz** [comment]
Is this resolved now, @lProvosl?
Maybe something else like your dark theme changer interferes, or the SWI you had was very outdated since it was from a backup, or ...?

**Comment by Revadike** [comment]
Closing for now
