### ISSUE TITLE
[Request] Boxed container color icon combinations

### ISSUE THREAD

**Issue by dokiiin** [Revadike/SteamWebIntegration#59]
Add color for combinations of icons for boxed container.

Icon combinations:
unownedIcon + cardIcon
unownedIcon + decommissionedIcon
unownedIcon + decommissionedIcon + cardIcon

**Comment by Revadike** [comment]
Done! Please check out https://github.com/Revadike/SteamWebIntegration/releases/tag/V1.12.0
