### ISSUE TITLE
Could not decode image when i try to install plugin

### ISSUE THREAD

**Issue by jojoPL1987** [Revadike/SteamWebIntegration#63]
I'm trying to install the Steam Web Integration 2.0.0 plugin from the Chrome Web Store. But I can't do it because the frame with the error appears on the Chrome Web Store page:

> Could not decode image: 'icon.svg'

I checked in Opera, Opera GX and Vivaldi.

**Comment by Revadike** [comment]
Will be fixed in next version

**Comment by Revadike** [comment]
Fixed in v2.1.0
