### ISSUE TITLE
Version 2.1.0 does not work

### ISSUE THREAD

**Issue by jojoPL1987** [Revadike/SteamWebIntegration#65]
I checked version 2.1.0 and it just doesn't work. I installed it but it just doesn't work. I click the plug-in button on the toolbar, select "Run" - it doesn't work. Refreshing the page - not working. "Factory reset" - does not work. I refresh the page - "does not work", again "Run" - does not work.

I checked the plugin on 2 pages and in the browser console I found the following entries.

I tried to run the plugin in Vivaldi 5.7.2921.60 (Stable channel) (64-bit).

From barter.vg:

> barter.vg/:1 Refused to load the font 'https://barter.vg/bundle/webfonts/fa-solid-900.woff2' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com/ data:".
> 
> barter.vg/:1 Refused to load the font 'https://barter.vg/bundle/webfonts/fa-solid-900.ttf' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com/ data:".
> 
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> barter.vg/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Regular.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> barter.vg/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Medium.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> barter.vg/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Regular.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> barter.vg/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Light.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> barter.vg/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Thin.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> content.js:349 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'iconsScale')
>     at init (content.js:349:37)

From SteamGifts.com:

> content.js:349 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'iconsScale')
>     at init (content.js:349:37)
> securepubads.g.doubleclick.net/tag/js/gpt.js:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> www.googletagmanager.com/gtag/js?id=G-ZVZMZGSZJZ:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> cmp.quantcast.com/choice/JTKTckadxK45t/www.steamgifts.com/choice.js?tag_version=V2:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> Denying load of <URL>. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> www.steamgifts.com/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Regular.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> www.steamgifts.com/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Medium.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> www.steamgifts.com/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Regular.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> www.steamgifts.com/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Light.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> www.steamgifts.com/:1 Denying load of chrome-extension://ibppednjgooiepmkgdcoppnmbhmieefh/fonts/Inter-Thin.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
> cmp_v3.js:148 USP is not accessible
> checkIfUspIsReady @ cmp_v3.js:148
> cmp_v3.js:148 USP is not accessible
> checkIfUspIsReady @ cmp_v3.js:148
> DevTools failed to load source map: Nie udało się wczytać treści mapy źródeł chrome-extension://ibedmjbicclcdfmghnkfldnplocgihna/lib/browser-polyfill.min.js.map: Błąd systemu: net::ERR_BLOCKED_BY_CLIENT

**Comment by Revadike** [comment]
Should be fixed in the next version
Submitted v2.1.1 for approval
