### ISSUE TITLE
It works but it doesn't always show the icons

### ISSUE THREAD

**Issue by jojoPL1987** [Revadike/SteamWebIntegration#66]
Version 2.1.1 works but doesn't always show icons. I know one situation. I warn you right away that the script in this situation had NO problems. For example, if the page loads information after the site has loaded. Example: SteamGifts.com with plugin installed:
https://chrome.google.com/webstore/detail/enhanced-steamgifts-steam/ibedmjbicclcdfmghnkfldnplocgihna
and active option #2.8 "Endless Scrolling".

It causes that instead of going to the second, third and next subpage of the main website, after moving to the bottom of the page, the content from the next subpage is automatically loaded. And as I have already written, the SWI script displays icons in this situation. Plugin in version 2.1.1 - no.

**Comment by Revadike** [comment]
Are you talking about the dynamic content option?

![image](https://user-images.githubusercontent.com/4411977/222772631-6cdcf504-6b9e-45a3-a03f-d65ca7b657a5.png)

**Comment by jojoPL1987** [comment]
Sorry. It was enough to change the settings to be good.
